config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :books, only: %i[index show]
  resources :carts, only: %i[show destroy]
  resources :line_items do
    member do
      post 'plus'
      post 'minus'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :line_items

  scope :latest_books, -> { order(published_at: :desc).take(8) }

  def real_price
    price / 100.to_f
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_book(book)
    current_item = line_items.find_by(book: book)
    if current_item
      current_item.plus!
    else
      current_item = line_items.build(book: book)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:total_price) / 100.to_f
  end
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  def total_price
    book.price * quantity
  end

  def plus!
    increment! :quantity
  end

  def minus!
    decrement! :quantity if quantity > 1
  end
end

app/models/user.rb
require 'open-uri'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :lockable, :timeoutable,
         :omniauthable, omniauth_providers: %i[github]

  has_one_attached :avatar

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email        = auth.info.email
      user.password     = Devise.friendly_token[0, 20]
      user.name         = auth.info.name # assuming the user model has a name
      downloaded_avatar = open(auth.info.image)
      user.avatar.attach(io: downloaded_avatar, filename: 'avatar')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.latest_books
  end

  def show
    @book = Book.find params[:id]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: [:show, :destroy]

  def show
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart

  private

    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart             = Cart.create
      session[:cart_id] = @cart.id
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/line_items_controller.rb
# frozen_string_literal: true

class LineItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: [:create, :destroy]
  before_action :set_line_item, only: [:destroy]

  def plus
    @line_item = LineItem.find params[:id]
    if @line_item
      @line_item.plus!
      respond_to do |format|
        format.html { redirect_to @line_item.cart }
        format.js
      end
    end
  end

  def minus
    @line_item = LineItem.find params[:id]
    if @line_item
      @line_item.minus!
      respond_to do |format|
        format.html { redirect_to @line_item.cart }
        format.js
      end
    end
  end

  def create
    book       = Book.find params[:book_id]
    @line_item = @cart.add_book(book)

    if @line_item.save
      redirect_to @line_item.cart
    else
      redirect_to book
    end
  end

  def destroy
    @line_item.destroy

    redirect_to @cart
  end

  private

    def set_line_item
      @line_item = LineItem.find params[:id]
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/books/_book.html.erb
<div class="col-3 my-2">
  <div class="book-image">
    <%= link_to book do %>
      <%= image_tag book.image, class: 'img-thumbnail' %>
    <% end %>
  </div>
  <div class="book-info">
    <small><%= book.title %></small>
    <br>
    <small class="text-muted"><%= book.author %></small>
  </div>
</div>

app/views/books/index.html.erb
<div class="row">
  <div class="col-8">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="pills-latest-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">最新</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-hot-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">热门</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-recommend-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">推荐</a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-latest-tab">
        <div class="row">
          <%= render @books, cache: true %>
        </div>
      </div>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-hot-tab">...</div>
      <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-recommend-tab">...</div>
    </div>
  </div>
  <div class="col-4">
    <div class="list-group">
      <a href="#" class="list-group-item list-group-item-action active">
        Cras justo odio
      </a>
      <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
      <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
      <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
      <a href="#" class="list-group-item list-group-item-action disabled" tabindex="-1" aria-disabled="true">Vestibulum
        at eros</a>
    </div>

    <div class="list-group my-5">
      <a href="#" class="list-group-item list-group-item-action active">
        Cras justo odio
      </a>
      <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
      <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
      <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
      <a href="#" class="list-group-item list-group-item-action disabled" tabindex="-1" aria-disabled="true">Vestibulum
        at eros</a>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-3">
    <div class="book-image">
      <%= image_tag @book.image, class: 'img-thumbnail' %>
    </div>
  </div>
  <div class="col-6">
    <div class="book-info">
      <h3 class="display-5"><%= @book.title %></h3>
      <small class="text-muted"><%= @book.author %></small>
    </div>
    <div class="book-summary overflow-auto my-4">
      <p> <%= @book.summary %> </p>
    </div>
    <div class="text-right">
      <div class="book-price">
        <span class="badge badge-secondary"><%= number_to_currency @book.real_price %></span>
      </div>
      <%= link_to '加入购物车', line_items_path(book_id: @book), method: :post, class: 'btn btn-light' %>
    </div>
  </div>
  <div class="col-3">

  </div>
</div>

app/views/carts/_cart.html.erb
<div class="text-right">
  <%= link_to '清空购物车', cart_path(cart), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: '确定清空购物车？' } %>
</div>
<table class="table">
  <thead>
  <tr>
    <th scope="col">书名</th>
    <th scope="col">定价</th>
    <th scope="col">数量</th>
    <th scope="col">操作</th>
  </tr>
  </thead>
  <tbody>
  <%= render cart.line_items, cache: true %>
  </tbody>
</table>

<h5 class="display-5">订单结算</h5>
<hr>
<div class="count text-right">
  <button type="button" disabled class="btn btn-secondary">合计金额：<%= number_to_currency cart.total_price %></button>
  <%= link_to '确定下单', '', class: 'btn btn-light' %>
</div>

app/views/carts/show.html.erb
<div class="text-center">
  <h3 class="display-5">我的购物车</h3>
</div>

<div class="my-3">
  <% if @cart.line_items.present? %>
    <div id="cart">
      <%= render @cart %>
    </div>
  <% else %>
    <p>购书车是空的哦～！
      <%= link_to '去看看吧！', root_url %>
    </p>
  <% end %>
</div>

app/views/common/_alert.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/common/_notice.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/home/welcome.html.erb
<div class="jumbotron bg-light text-center">
  <h1 class="display-4">Welcome to webook!</h1>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'webook', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, size: '21x21' %>
            <% else %>
              <%= current_user.email %>
            <% end %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <div class="dropdown-divider"></div>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <title>Webook</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/navbar' %>

<div class="container my-5">
  <%= render 'common/alert' %>
  <%= render 'common/notice' %>

  <%= yield %>

</div>

</body>
</html>

app/views/line_items/_line_item.html.erb
<tr>
  <td>
    <%= link_to line_item.book do %>
      <%= line_item.book.title %>
    <% end %>
  </td>
  <td><%= number_to_currency line_item.book.real_price %></td>
  <td>
    <div class="btn-group-sm" role="group">
      <%= link_to '-', minus_line_item_path(line_item), method: :post, remote: true, class: 'btn btn-sm btn-light' %>
      <%= line_item.quantity %>
      <%= link_to '+', plus_line_item_path(line_item), method: :post, remote: true, class: 'btn btn-sm btn-light' %>
    </div>
  </td>
  <td>
    <%= link_to '删除', line_item, method: :delete, class: 'btn btn-sm btn-light' %>
  </td>
</tr>

app/views/line_items/minus.js.erb
$("#cart").html("<%= j render @line_item.cart %>")

app/views/line_items/plus.js.erb
$("#cart").html("<%= j render @line_item.cart %>")

app/views/users/shared/_links.html.erb
<div class="form-text text-muted">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br/>
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br/>
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br/>
  <% end -%>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br/>
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br/>
  <% end -%>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
      <br/>
    <% end -%>
  <% end -%>
</div>